apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
      - name: websocket
        image: your-repo/websocket-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: AUTH_SERVICE_ADDR
          value: "auth-service:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: websocket
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: websocket